### PR TITLE
Fixed library for Rust 1.0.0

### PR DESCRIPTION
**Pull request by fizyk20**
These changes make the library compile with Rust 1.0.0 and the tests pass (tested on Windows and Arch Linux).

I also split the library into 4 modules: mpz, mpq, mpf and rand, for the sake of readability.

### CODE REVIEW

**Comment by vks** [comment]
I think @thestinger stopped maintaining rust-gmp.

**Comment by fizyk20** [comment]
That would be a shame. I only found one alternative library and this one is much more straightforward to use.

**Comment by thestinger** [comment]
You're free to fork this repository and maintain it yourself. I'm not going to take down the original though.

I'm not working on anything Rust related anymore. The core developers are underhanded liars interested only in playing political games rather than dealing with technical issues. I have no interest in being part of a community following leadership like that.

**Comment by thestinger** [comment]
Oh, and I don't like the language anyway... it needed to be improved in various substantial ways before being stabilized. I stopped being involved in the development so I never had the chance to push for fixing the major issues that are left. It's not even memory safe at all... but that's not my problem anymore.

**Comment by fizyk20** [comment]
Sorry to hear you have such bad experiences with the community. I sure hope that was an isolated case or that things improved. I'll keep on tinkering with the library by myself then and thanks for what you've done!

**Comment by vks** [comment]
@fizyk20 Would it be possible to leave you branch on github? I think others might want to use gmp with Rust 1.0, and your changes would be very useful for that.

**Comment by fizyk20** [comment]
Yeah, it would, but my current master branch has changes from rust1.0 as well as some more, so it would be a bit redundant.

**Comment by vks** [comment]
@fizyk20 Oh, I did not realize you merged it to your master, sorry. Everything is fine then. :)

**Comment by Moredread** [comment]
Would you mind adding a notice in the README that the package is abandoned? I have come atleast twice to this project when looking for a gmp binding (it is still higher ranked in google for "rust gmp" than the alternatives), and wondered whether it is the active one.

It esp. would help newbies, that don't have the experience judging the activity of a project quickly IMO.

**Pull request closed without merging**
